variables:
  - namespace: circadian-bri
    type: brightness
    unit: percentage
styles:
  circadian-lighting:
    brightness: $circadian-bri
    temperature:
      namespace: circadian-temp
      type: temperature
      unit: kelvin
layers:
  primaryCircadian:
    scene: circadian
    style: circadian-lighting
lights:
  - entityId: light.living_room
    layers:
      - scene: theater
        style:
          temperature: 2700k
          brightness: $theater-bri
      - primaryCircadian