script:
  init_living_room:
    alias: "SCRIPT: Initialize living_room"
    sequence:
      - alias: Get highest priority scene for light living_room
        choose:
          - alias: if theater is on
            conditions:
              - alias: "CONDITION: check theater toggle is on"
                condition: state
                entity_id: input_boolean.fsfr_scene_theater
                state: on
            sequence:
              - alias: "ACTION: apply scene theater to light"
                service: script.turn_on
                target:
                  entity_id: script.apply_theater_to_living_room
          - alias: if circadian is on
            conditions:
              - alias: "CONDITION: check circadian toggle is on"
                condition: state
                entity_id: input_boolean.fsfr_scene_circadian
                state: on
            sequence:
              - alias: "ACTION: apply scene circadian to light"
                service: script.turn_on
                target:
                  entity_id: script.apply_circadian_to_living_room
        default:
          - alias: "ACTION: turn off light"
            service: light.turn_off
            target:
              entity_id: light.living_room