script:
  check_living_room_circadian_check:
    sequence:
      - alias: some alias
        choose:
          - alias: if circadian is off
            conditions:
              - condition: state
                entity_id: input_boolean.fsfr_scene_circadian
                state: 'off'
            sequence:
              - service: script.turn_on
                target:
                  entity_id: script.watch this scene is on
                data:
                  variables: {}
          - alias: if circadian is on
            conditions:
              - condition: state
                entity_id: input_boolean.fsfr_scene_circadian
                state: 'on'
            sequence:
              - service: script.turn_on
                target:
                  entity_id: script.watch current scene off
                data:
                  variables: {}
        default: []
