script:
  light.living_room theater check script:
    sequence:
      - alias: my alias
        choose:
          - alias: my new choice
            conditions:
              - condition: state
                entity_id: input_boolean.fsfr_scene_theater
                state: 'on'
              - condition: state
                entity_id: input_select.fsfr_light.living_room_scenes
                state: theater
            sequence:
              - service: script.turn_on
                entity_id: util_script_for_var
                data:
                  variables:
                    var_name: theater-bri
                    light_id: light.living_room
                    scene_id: theater
              - service: light.turn_on
                target:
                  entity_id: light.living_room
                data:
                  temperature: 2700k
                  brightness_pct: "{{ states('input_number.fsfr_theater_bri') | int}}"
        default:
          - service: script.check_primaryCircadian
  light.living_room circadian check script:
    sequence:
      - alias: my alias
        choose:
          - alias: my new choice
            conditions:
              - condition: state
                entity_id: input_boolean.fsfr_scene_circadian
                state: 'on'
              - condition: state
                entity_id: input_select.fsfr_light.living_room_scenes
                state: circadian
            sequence:
              - service: script.turn_on
                entity_id: util_script_for_var
                data:
                  variables:
                    var_name: circadian-bri
                    light_id: light.living_room
                    scene_id: circadian
              - service: script.turn_on
                entity_id: util_script_for_var
                data:
                  variables:
                    var_name: circadian-temp
                    light_id: light.living_room
                    scene_id: circadian
              - service: light.turn_on
                target:
                  entity_id: light.living_room
                data:
                  brightness_pct: '"{{ states(''input_number.fsfrcircadian-bri'') | int}}"'
                  kelvin: '"{{ states(''input_number.fsfrcircadian-temp'') | int}}"'
        default:
          - service: light.turn_off
            entity_id: l
